alias ll='/bin/ls -lFGh --color'
alias lla='/bin/ls -lFGhA --color'
alias la='/bin/ls -AFG --color'
alias ls='/bin/ls -FG --color'
alias sl='ls'
alias anzeigen='defaults write com.apple.finder AppleShowAllFiles 1 && killall Finder'
alias ausblenden='defaults write com.apple.finder AppleShowAllFiles 0 && killall Finder'



# alias pixelextend='rm -rf ~/Library/Containers/com.pixelmatorteam.pixelmator.x.trial/'
# alias sshcip='ssh -Y  m.lohmann@login.cip.physik.uni-goettingen.de'
alias finalcutextend='rm ~/Library/Application\ Support/.ffuserdata'
alias pixelextend='rm -rf ~/Library/Group\ Containers/4R6749AYRE.com.pixelmator/'
alias pull='git pull'
alias push='git push'
alias sshcip='ssh -X -J m.lohmann@login.cip.physik.uni-goettingen.de c079'
alias sshpiethernet='ssh pi@192.168.2.2'
alias sshpigeist='ssh pi@10.10.182.103'
alias sshpiheist='ssh pi@192.168.1.5'
alias vim='nvim'
alias cds='cd ~/Salus/citizen-app/ && ANDROID_HOME="$HOME/Android/Sdk" nix-shell --arg run \"zsh\"'
