alias ll='/bin/ls -lFGh'
alias lla='/bin/ls -lFGha'
alias la='/bin/ls -aFG'
alias ls='/bin/ls -FG'
alias sl='ls'
alias anzeigen='defaults write com.apple.finder AppleShowAllFiles 1 && killall Finder'
alias ausblenden='defaults write com.apple.finder AppleShowAllFiles 0 && killall Finder'



#alias pixelextend='rm -rf ~/Library/Containers/com.pixelmatorteam.pixelmator.x.trial/'
#alias sshcip='ssh -Y  m.lohmann@login.cip.physik.uni-goettingen.de'
alias cdD='cd ~/Documents/Uni/Master/Thesis/DeepLearning'
alias cdO='cd ~/tempODL/src/odl/odl'
alias cdO='cd ~/tempODL/src/odl/odl'
alias cdd='cd ~/Uni/Master/Thesis/DeepLearning'
alias cdda='cd ~/Uni/Master/Thesis_Data'
alias cdm='cd ~/Uni/Master/Thesis/'
alias cdr='cd ~/Uni/Master/Thesis/reconstructions'
alias cim='vimn'
alias finalcutextend='rm ~/Library/Application\ Support/.ffuserdata'
alias lstex='ls *.tex'
alias matlab='/Applications/MATLAB_R2017a.app/bin/matlab'
alias pixelextend='rm -rf ~/Library/Group\ Containers/4R6749AYRE.com.pixelmator/'
alias pull='git pull'
alias push='git push'
alias sshcip='ssh -X -J m.lohmann@login.cip.physik.uni-goettingen.de c079'
alias sshpiethernet='ssh pi@192.168.2.2'
alias sshpigeist='ssh pi@10.10.182.103'
alias sshpiheist='ssh pi@192.168.1.5'
alias updateodl='source activate odlenv && pip install git+git://github.com/odlgroup/odl@master && source deactivate'
alias vim='nvim'
alias vimtorstate='vim /Users/Michael/Library/Application Support/TorBrowser-Data/Tor/state'
